### ISSUE TITLE
AlertRules fail to deploy

### ISSUE THREAD

**Issue by cwilliamsipc** [SecureHats/Sentinel-playground#21] opened 2021-12-30 21:20 UTC
Everything works until the template tries to deploy the AlertRules.  

Here is the error summary:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"DeploymentScriptDownloadFailure","message":"The deployment script execution failed because the primary or supporting scripts could not be downloaded successfully due to multiple errors. First error:\r\nMicrosoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information."}]}

The following is the raw error: 
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "code": "DeploymentScriptDownloadFailure",
      "message": "The deployment script execution failed because the primary or supporting scripts could not be downloaded successfully due to multiple errors. First error:\r\nMicrosoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information."
    }
  ]
}

**Comment by cwilliamsipc** [comment] 2021-12-30 21:34
Here is the full status message.  I tried deployments in EastUS and SouthCentralUS.

 "status": "failed",
    "error": {
        "code": "DeploymentScriptDownloadFailure",
        "message": "The deployment script execution failed because the primary or supporting scripts could not be downloaded successfully due to multiple errors. First error:\r\nMicrosoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200. Please refer to https://aka.ms/DeploymentScriptsTroubleshoot for more deployment script information.",
        "details": [
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200"
            },
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200"
            },
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200"
            },
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200"
            },
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200"
            },
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "Microsoft.PowerShell.Commands.HttpResponseException: Response status code does not indicate success: 404 (Not Found).\n   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 79\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200"
            },
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "System.Management.Automation.RuntimeException: Failed to download external script: 404: Not Found\r\nat Start-SystemDeploymentScriptDownloadFile, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 91\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 200"
            },
            {
                "code": "DeploymentScriptDownloadFailure",
                "message": "System.Management.Automation.RuntimeException: Failed to download external script: Failed to download external script: 404: Not Found\r\nat <ScriptBlock>, /mnt/azscripts/azscriptinput/DeploymentScript.ps1: line 219"
            }
        ]
    }
}

**Comment by azurekid** [comment] 2022-01-05 21:15
Hi @cwilliamsipc 
Thanks for you valuable feedback!
I will pick this up tomorrow morning and give you an update when I have this fixed.
Expect to have this fixed within the next 24h

**Comment by cwilliamsipc** [comment] 2022-01-05 21:16
Thanks Rogier!!

**Comment by azurekid** [comment] 2022-01-06 18:40
Hi @cwilliamsipc,

I was able to reproduce the error, and I'm working on a fix right now.
The name of the script was changed from Enable-AlertRules.ps1 to Update-DetectionRules.ps1 causing the deployment to fail.

The deployment template has been updated and it seems to be working again.
If you have any other issues, or feature request, please reach out!

![image](https://user-images.githubusercontent.com/40334679/148433945-ecf6aa3b-1d1e-4771-bcdb-3fa18dc5c7e7.png)

**Comment by cwilliamsipc** [comment] 2022-01-06 18:42
Awesome!  Thank you so much!  This is such a helpful tool to use for demos!

**Comment by azurekid** [comment] 2022-01-06 18:49
Are there any data sources you would likec to see added to the playground?



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Closed** 2022-01-06 20:35 UTC
